# Generated by Django 3.2.15 on 2022-08-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeowner',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuestUser',
        ),
        migrations.DeleteModel(
            name='StoreOwner',
        ),
    ]
