# Generated by Django 3.2.15 on 2022-08-22 13:43

from django.db import migrations

def create_customers(apps, schema_editor):
    Customer = apps.get_model('store', 'Customer')
    User = apps.get_model('auth', 'User')
    customers = [
        Customer(user=user, name=None, email=None)
        for user in User.objects.filter(customer=None)
    ]
    Customer.objects.bulk_create(customers)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_customers),
    ]




